### ISSUE TITLE
Pushover postfields issue

### ISSUE THREAD

**Issue by sivel** [stfnm/weechat-scripts#23]
Up until today pushover support was working fine for me, but it is now failing.

Currently in `notify_pushover`, `postfields` is being joined with a `;`.  Changing that to `&` resolves the problems.

```
my $hash = { "post"  => 1, "postfields" => join("&", @post) };
```

instead of:

```
my $hash = { "post"  => 1, "postfields" => join(";", @post) };
```

Also, as a side note, the version here in this repo is `2.0`, where as what is at https://weechat.org/scripts/source/pushover.pl.html/ is `1.4`

**Comment by stfnm** [comment]
Fixed by commit 69968941502fe4f476e06d70a73e39ba1397fc87.

Yeah, with the version bump to 2.0 I decided to drop support for the other notification services, since I only use pushover.net myself and didn't wanna keep up with the other APIs anymore without being able to test them properly. Instead people can use pushover.pl's notification signal and plug it into /trigger and /exec to use any other service they like.

Just haven't gotten around to pull-request that to the upstream/official scripts repo yet. I'll try to do that soon as there's a good reason now.
